### ISSUE TITLE
Social Share disappeared 

### ISSUE THREAD

**Issue by ssmirti** [nydailynews/vox-nihili#2]
http://interactive.nydailynews.com/project/game-of-thrones-house/

![screen shot 2018-06-21 at 2 51 43 pm](https://user-images.githubusercontent.com/25779035/41739293-a3882074-7562-11e8-9adc-ab0138ee890e.png)

**Comment by freejoe76** [comment]
This is fixed http://interactive.nydailynews.com/project/game-of-thrones-house/
